<?php
$escape = $this->plugin('escapeHtml'); ?>

<tr id="export-<?php echo $id; ?>">
    <td>
        <?php echo $escape($this->i18n()->dateFormat($job->started())); ?>
    </td>
    <td>
        <?php echo $filename . $extension; ?>
    </td>
    <td>
        <?php echo $this->translate($resourceType); ?>
    </td>
    <td>
        <?php echo $this->hyperlink($this->translate(" $resourcesCount resource(s)"), "/admin/$query", ['class' => 'o-icon-external', 'target' => '_blank']); ?>
    </td>
    <td>
        <div>
            <?php echo $escape($this->translate($job->status())); ?>
        </div>
        <span>
            <?php echo $this->hyperlink($this->translate('Job details'), $this->url('admin/id', ['controller' => 'job', 'action' => 'show', 'id' => $job->id()])); ?>
        </span>
        <?php if ($job->log()): ?>
            /
            <span>
                <?php echo $this->hyperlink($this->translate('Log'), $this->url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()]), ['target' => '_blank']); ?>
            </span>
        <?php endif; ?>
    </td>
    <td>
        <ul class="actions">
            <li>
                <a class="o-icon-install" href="<?php echo $fileUri ?>" download target="_blank"></a>
            </li>
            <li>
                <a class="o-icon-delete" href="<?php echo $this->url('admin/export/delete', [], ['query' => ['id' => $id, 'filename' => $filename . $extension]]); ?>"> </a>
            </li>
        </ul>
    </td>
</tr>