<?php
$translate = $this->plugin('translate');
$escapeHtml = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/export.css', 'Export'));
?>

<?php echo $this->pageTitle($this->translate('Export list'), 1, $this->translate('Export')); ?>
<div>
    <p><?php echo $this->translate('Previous exports from jobs')?></p>
    <?php if (empty($downloads)) {
    echo $this->translate('No exports yet');
} ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <th class="column-title"><a><?php echo $this->translate('Title') ?> </a></th>
        <th class="column-actions"><a><?php echo $this->translate('Actions') ?> </a></th>
    </thead>
    <tbody>
        <?php foreach ($downloads as $download) {
                $filePath = "/files/Export/" . $download ?>
        <tr>
            <td>
                <a href="<?php echo $filePath ?>" > <?php echo $download ?> </a>
            </td>
            <td>
                <ul class="actions">
                    <li>
                    <a class="o-icon-delete" href="<?php echo $this->url('admin/export/delete', [], ['query' => ['file_name' => $download]]); ?>"> </a>
                    </li>
                    <li>
                        <a class="o-icon-install" href="<?php echo $filePath ?>" ></a>
                    </li>
                </ul>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
</div>
